logging:
  level:
    com.ub: debug
server:
  port: 8082

spring:
  application:
    name: inventory-service
  datasource:
    initialization-mode: embedded
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  h2:
    console:
      enabled: true
  artemis:
    user: artemis
    password: simetraehcapa